// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mcbeam-helloworld-srv.proto

package mcbeamhelloworldsrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for McbeamHelloworldSrv service

func NewMcbeamHelloworldSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for McbeamHelloworldSrv service

type McbeamHelloworldSrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (McbeamHelloworldSrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (McbeamHelloworldSrv_PingPongService, error)
}

type mcbeamHelloworldSrvService struct {
	c    client.Client
	name string
}

func NewMcbeamHelloworldSrvService(name string, c client.Client) McbeamHelloworldSrvService {
	return &mcbeamHelloworldSrvService{
		c:    c,
		name: name,
	}
}

func (c *mcbeamHelloworldSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "McbeamHelloworldSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcbeamHelloworldSrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (McbeamHelloworldSrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "McbeamHelloworldSrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mcbeamHelloworldSrvServiceStream{stream}, nil
}

type McbeamHelloworldSrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type mcbeamHelloworldSrvServiceStream struct {
	stream client.Stream
}

func (x *mcbeamHelloworldSrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *mcbeamHelloworldSrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mcbeamHelloworldSrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mcbeamHelloworldSrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mcbeamHelloworldSrvService) PingPong(ctx context.Context, opts ...client.CallOption) (McbeamHelloworldSrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "McbeamHelloworldSrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mcbeamHelloworldSrvServicePingPong{stream}, nil
}

type McbeamHelloworldSrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type mcbeamHelloworldSrvServicePingPong struct {
	stream client.Stream
}

func (x *mcbeamHelloworldSrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *mcbeamHelloworldSrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *mcbeamHelloworldSrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mcbeamHelloworldSrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for McbeamHelloworldSrv service

type McbeamHelloworldSrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, McbeamHelloworldSrv_StreamStream) error
	PingPong(context.Context, McbeamHelloworldSrv_PingPongStream) error
}

func RegisterMcbeamHelloworldSrvHandler(s server.Server, hdlr McbeamHelloworldSrvHandler, opts ...server.HandlerOption) error {
	type mcbeamHelloworldSrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type McbeamHelloworldSrv struct {
		mcbeamHelloworldSrv
	}
	h := &mcbeamHelloworldSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&McbeamHelloworldSrv{h}, opts...))
}

type mcbeamHelloworldSrvHandler struct {
	McbeamHelloworldSrvHandler
}

func (h *mcbeamHelloworldSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.McbeamHelloworldSrvHandler.Call(ctx, in, out)
}

func (h *mcbeamHelloworldSrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.McbeamHelloworldSrvHandler.Stream(ctx, m, &mcbeamHelloworldSrvStreamStream{stream})
}

type McbeamHelloworldSrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type mcbeamHelloworldSrvStreamStream struct {
	stream server.Stream
}

func (x *mcbeamHelloworldSrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mcbeamHelloworldSrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mcbeamHelloworldSrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mcbeamHelloworldSrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *mcbeamHelloworldSrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.McbeamHelloworldSrvHandler.PingPong(ctx, &mcbeamHelloworldSrvPingPongStream{stream})
}

type McbeamHelloworldSrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type mcbeamHelloworldSrvPingPongStream struct {
	stream server.Stream
}

func (x *mcbeamHelloworldSrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *mcbeamHelloworldSrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mcbeamHelloworldSrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mcbeamHelloworldSrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *mcbeamHelloworldSrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
