// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/pay.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Pay service

func NewPayEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Pay service

type PayService interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...client.CallOption) (*CreateOrderRes, error)
	QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...client.CallOption) (*QueryOrderRes, error)
	CompleteOrder(ctx context.Context, in *CompleteOrderReq, opts ...client.CallOption) (*CompleteOrderRes, error)
	SavePayToken(ctx context.Context, in *SavePayTokenReq, opts ...client.CallOption) (*SavePayTokenRes, error)
}

type payService struct {
	c    client.Client
	name string
}

func NewPayService(name string, c client.Client) PayService {
	return &payService{
		c:    c,
		name: name,
	}
}

func (c *payService) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...client.CallOption) (*CreateOrderRes, error) {
	req := c.c.NewRequest(c.name, "Pay.CreateOrder", in)
	out := new(CreateOrderRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payService) QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...client.CallOption) (*QueryOrderRes, error) {
	req := c.c.NewRequest(c.name, "Pay.QueryOrder", in)
	out := new(QueryOrderRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payService) CompleteOrder(ctx context.Context, in *CompleteOrderReq, opts ...client.CallOption) (*CompleteOrderRes, error) {
	req := c.c.NewRequest(c.name, "Pay.CompleteOrder", in)
	out := new(CompleteOrderRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payService) SavePayToken(ctx context.Context, in *SavePayTokenReq, opts ...client.CallOption) (*SavePayTokenRes, error) {
	req := c.c.NewRequest(c.name, "Pay.SavePayToken", in)
	out := new(SavePayTokenRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pay service

type PayHandler interface {
	CreateOrder(context.Context, *CreateOrderReq, *CreateOrderRes) error
	QueryOrder(context.Context, *QueryOrderReq, *QueryOrderRes) error
	CompleteOrder(context.Context, *CompleteOrderReq, *CompleteOrderRes) error
	SavePayToken(context.Context, *SavePayTokenReq, *SavePayTokenRes) error
}

func RegisterPayHandler(s server.Server, hdlr PayHandler, opts ...server.HandlerOption) error {
	type pay interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, out *CreateOrderRes) error
		QueryOrder(ctx context.Context, in *QueryOrderReq, out *QueryOrderRes) error
		CompleteOrder(ctx context.Context, in *CompleteOrderReq, out *CompleteOrderRes) error
		SavePayToken(ctx context.Context, in *SavePayTokenReq, out *SavePayTokenRes) error
	}
	type Pay struct {
		pay
	}
	h := &payHandler{hdlr}
	return s.Handle(s.NewHandler(&Pay{h}, opts...))
}

type payHandler struct {
	PayHandler
}

func (h *payHandler) CreateOrder(ctx context.Context, in *CreateOrderReq, out *CreateOrderRes) error {
	return h.PayHandler.CreateOrder(ctx, in, out)
}

func (h *payHandler) QueryOrder(ctx context.Context, in *QueryOrderReq, out *QueryOrderRes) error {
	return h.PayHandler.QueryOrder(ctx, in, out)
}

func (h *payHandler) CompleteOrder(ctx context.Context, in *CompleteOrderReq, out *CompleteOrderRes) error {
	return h.PayHandler.CompleteOrder(ctx, in, out)
}

func (h *payHandler) SavePayToken(ctx context.Context, in *SavePayTokenReq, out *SavePayTokenRes) error {
	return h.PayHandler.SavePayToken(ctx, in, out)
}
