// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: proto/gsm.proto

package gsm

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PlayerGameStatus int32

const (
	PlayerGameStatus_Invalid PlayerGameStatus = 0
	PlayerGameStatus_Joined  PlayerGameStatus = 1 // 已加入
	PlayerGameStatus_Leave   PlayerGameStatus = 2 // 已离开
)

// Enum value maps for PlayerGameStatus.
var (
	PlayerGameStatus_name = map[int32]string{
		0: "Invalid",
		1: "Joined",
		2: "Leave",
	}
	PlayerGameStatus_value = map[string]int32{
		"Invalid": 0,
		"Joined":  1,
		"Leave":   2,
	}
)

func (x PlayerGameStatus) Enum() *PlayerGameStatus {
	p := new(PlayerGameStatus)
	*p = x
	return p
}

func (x PlayerGameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerGameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gsm_proto_enumTypes[0].Descriptor()
}

func (PlayerGameStatus) Type() protoreflect.EnumType {
	return &file_proto_gsm_proto_enumTypes[0]
}

func (x PlayerGameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerGameStatus.Descriptor instead.
func (PlayerGameStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{0}
}

// 房间类型
type RoomType int32

const (
	RoomType_NormalRoom  RoomType = 0 // 普通房
	RoomType_PrivateRoom RoomType = 1 // 私人房
	RoomType_ClubRoom    RoomType = 2 // 俱乐部房间
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "NormalRoom",
		1: "PrivateRoom",
		2: "ClubRoom",
	}
	RoomType_value = map[string]int32{
		"NormalRoom":  0,
		"PrivateRoom": 1,
		"ClubRoom":    2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gsm_proto_enumTypes[1].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_proto_gsm_proto_enumTypes[1]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{0}
}

// 创建房间请求
type CreateRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId     string            `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                                                               // 游戏ID
	Properties string            `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`                                                                                     // 房间参数，内容自定义
	RoomId     string            `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                                               // 房间ID
	Metadata   map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 私有数据
	Labels     []string          `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`                                                                                             // 标签
	Aliases    []string          `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`                                                                                           // 别名
}

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateRoomReq) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

func (x *CreateRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateRoomReq) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateRoomReq) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type GamePlayerStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: bson:"openid"
	Openid string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"` // 玩家ID
	//@inject_tag: bson:"metadata"
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//@inject_tag: bson:"nickname"
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	//  int32 type = 4;
	//@inject_tag: bson:"avatar"
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"` // 头像
	//@inject_tag: bson:"status"
	Status PlayerGameStatus `protobuf:"varint,6,opt,name=status,proto3,enum=gsm.PlayerGameStatus" json:"status,omitempty"` // 玩家状态
}

func (x *GamePlayerStats) Reset() {
	*x = GamePlayerStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayerStats) ProtoMessage() {}

func (x *GamePlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayerStats.ProtoReflect.Descriptor instead.
func (*GamePlayerStats) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{2}
}

func (x *GamePlayerStats) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GamePlayerStats) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GamePlayerStats) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GamePlayerStats) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GamePlayerStats) GetStatus() PlayerGameStatus {
	if x != nil {
		return x.Status
	}
	return PlayerGameStatus_Invalid
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       string             `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                       // 房间ID
	ServerId     string             `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                 // 房间所在服务器信息
	GameGid      string             `protobuf:"bytes,3,opt,name=game_gid,json=gameGid,proto3" json:"game_gid,omitempty"`                    // 游戏ID
	MatchCid     string             `protobuf:"bytes,4,opt,name=match_cid,json=matchCid,proto3" json:"match_cid,omitempty"`                 // 房间匹配码，场次ID match_cid
	MaxPlayerNum int32              `protobuf:"varint,5,opt,name=max_player_num,json=maxPlayerNum,proto3" json:"max_player_num,omitempty"`  // 房间内参与人数上限
	Owner        string             `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`                                       // 房间创建者
	Properties   string             `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`                             // 房间属性
	CreateTime   int64              `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`         // 房间创建时间
	Labels       []string           `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`                                    // 标签
	Aliases      []string           `protobuf:"bytes,12,rep,name=aliases,proto3" json:"aliases,omitempty"`                                  // 别名
	Players      []*GamePlayerStats `protobuf:"bytes,13,rep,name=players,proto3" json:"players,omitempty"`                                  // 玩家列表
	Type         RoomType           `protobuf:"varint,14,opt,name=type,proto3,enum=gsm.RoomType" json:"type,omitempty"`                     // 房间类型
	ShareCode    string             `protobuf:"bytes,15,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`             // 分享码
	PlatAid      int32              `protobuf:"varint,16,opt,name=plat_aid,json=platAid,proto3" json:"plat_aid,omitempty"`                  // 平台
	MinPlayerNum int32              `protobuf:"varint,17,opt,name=min_player_num,json=minPlayerNum,proto3" json:"min_player_num,omitempty"` // 最小玩家数量
	Stats        string             `protobuf:"bytes,18,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RoomInfo) GetGameGid() string {
	if x != nil {
		return x.GameGid
	}
	return ""
}

func (x *RoomInfo) GetMatchCid() string {
	if x != nil {
		return x.MatchCid
	}
	return ""
}

func (x *RoomInfo) GetMaxPlayerNum() int32 {
	if x != nil {
		return x.MaxPlayerNum
	}
	return 0
}

func (x *RoomInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RoomInfo) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

func (x *RoomInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RoomInfo) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RoomInfo) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *RoomInfo) GetPlayers() []*GamePlayerStats {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfo) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_NormalRoom
}

func (x *RoomInfo) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *RoomInfo) GetPlatAid() int32 {
	if x != nil {
		return x.PlatAid
	}
	return 0
}

func (x *RoomInfo) GetMinPlayerNum() int32 {
	if x != nil {
		return x.MinPlayerNum
	}
	return 0
}

func (x *RoomInfo) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

// 创建房间请求回复
type CreateRoomRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err  string    `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`   // 请求错误提示
	Room *RoomInfo `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"` // 创建成功的房间信息
}

func (x *CreateRoomRsp) Reset() {
	*x = CreateRoomRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRsp) ProtoMessage() {}

func (x *CreateRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRsp.ProtoReflect.Descriptor instead.
func (*CreateRoomRsp) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRsp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *CreateRoomRsp) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

type CheckRoomExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	GameGid  string `protobuf:"bytes,3,opt,name=game_gid,json=gameGid,proto3" json:"game_gid,omitempty"`
}

func (x *CheckRoomExistsReq) Reset() {
	*x = CheckRoomExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomExistsReq) ProtoMessage() {}

func (x *CheckRoomExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomExistsReq.ProtoReflect.Descriptor instead.
func (*CheckRoomExistsReq) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRoomExistsReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CheckRoomExistsReq) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CheckRoomExistsReq) GetGameGid() string {
	if x != nil {
		return x.GameGid
	}
	return ""
}

type CheckRoomExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *CheckRoomExistsRsp) Reset() {
	*x = CheckRoomExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomExistsRsp) ProtoMessage() {}

func (x *CheckRoomExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomExistsRsp.ProtoReflect.Descriptor instead.
func (*CheckRoomExistsRsp) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{6}
}

func (x *CheckRoomExistsRsp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// 获取指定房间信息请求
type GetRoomInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *GetRoomInfoReq) Reset() {
	*x = GetRoomInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoReq) ProtoMessage() {}

func (x *GetRoomInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoReq.ProtoReflect.Descriptor instead.
func (*GetRoomInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomInfoReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomInfoReq) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// 请求的房间信息回复
type GetRoomInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err  string    `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`   // 错误标识
	Room *RoomInfo `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"` // 房间信息
}

func (x *GetRoomInfoRsp) Reset() {
	*x = GetRoomInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRsp) ProtoMessage() {}

func (x *GetRoomInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRsp.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRsp) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoomInfoRsp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *GetRoomInfoRsp) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

type KickPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Openid string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Admin  string `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *KickPlayerReq) Reset() {
	*x = KickPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerReq) ProtoMessage() {}

func (x *KickPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerReq.ProtoReflect.Descriptor instead.
func (*KickPlayerReq) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{9}
}

func (x *KickPlayerReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *KickPlayerReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *KickPlayerReq) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type KickPlayerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *KickPlayerRsp) Reset() {
	*x = KickPlayerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gsm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPlayerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRsp) ProtoMessage() {}

func (x *KickPlayerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gsm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRsp.ProtoReflect.Descriptor instead.
func (*KickPlayerRsp) Descriptor() ([]byte, []int) {
	return file_proto_gsm_proto_rawDescGZIP(), []int{10}
}

func (x *KickPlayerRsp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proto_gsm_proto protoreflect.FileDescriptor

var file_proto_gsm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x67, 0x73, 0x6d, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x8e, 0x02, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x65, 0x73, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x89, 0x02, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a,
	0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf0, 0x03, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x47, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x5f, 0x61, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x74,
	0x41, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x69, 0x6e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22,
	0x44, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x65, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f,
	0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x47, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x56, 0x0a, 0x0d, 0x4b, 0x69, 0x63,
	0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x22, 0x21, 0x0a, 0x0d, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x2a, 0x36, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x10, 0x02, 0x2a, 0x39, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6c, 0x75,
	0x62, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x02, 0x32, 0xf9, 0x01, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x6d,
	0x73, 0x12, 0x36, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x12, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x67, 0x73, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f,
	0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x4b,
	0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x73, 0x6d, 0x2e,
	0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x67, 0x73, 0x6d, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67,
	0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gsm_proto_rawDescOnce sync.Once
	file_proto_gsm_proto_rawDescData = file_proto_gsm_proto_rawDesc
)

func file_proto_gsm_proto_rawDescGZIP() []byte {
	file_proto_gsm_proto_rawDescOnce.Do(func() {
		file_proto_gsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gsm_proto_rawDescData)
	})
	return file_proto_gsm_proto_rawDescData
}

var file_proto_gsm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_gsm_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_gsm_proto_goTypes = []interface{}{
	(PlayerGameStatus)(0),      // 0: gsm.PlayerGameStatus
	(RoomType)(0),              // 1: gsm.RoomType
	(*Empty)(nil),              // 2: gsm.Empty
	(*CreateRoomReq)(nil),      // 3: gsm.CreateRoomReq
	(*GamePlayerStats)(nil),    // 4: gsm.GamePlayerStats
	(*RoomInfo)(nil),           // 5: gsm.RoomInfo
	(*CreateRoomRsp)(nil),      // 6: gsm.CreateRoomRsp
	(*CheckRoomExistsReq)(nil), // 7: gsm.CheckRoomExistsReq
	(*CheckRoomExistsRsp)(nil), // 8: gsm.CheckRoomExistsRsp
	(*GetRoomInfoReq)(nil),     // 9: gsm.GetRoomInfoReq
	(*GetRoomInfoRsp)(nil),     // 10: gsm.GetRoomInfoRsp
	(*KickPlayerReq)(nil),      // 11: gsm.KickPlayerReq
	(*KickPlayerRsp)(nil),      // 12: gsm.KickPlayerRsp
	nil,                        // 13: gsm.CreateRoomReq.MetadataEntry
	nil,                        // 14: gsm.GamePlayerStats.MetadataEntry
}
var file_proto_gsm_proto_depIdxs = []int32{
	13, // 0: gsm.CreateRoomReq.metadata:type_name -> gsm.CreateRoomReq.MetadataEntry
	14, // 1: gsm.GamePlayerStats.metadata:type_name -> gsm.GamePlayerStats.MetadataEntry
	0,  // 2: gsm.GamePlayerStats.status:type_name -> gsm.PlayerGameStatus
	4,  // 3: gsm.RoomInfo.players:type_name -> gsm.GamePlayerStats
	1,  // 4: gsm.RoomInfo.type:type_name -> gsm.RoomType
	5,  // 5: gsm.CreateRoomRsp.room:type_name -> gsm.RoomInfo
	5,  // 6: gsm.GetRoomInfoRsp.room:type_name -> gsm.RoomInfo
	3,  // 7: gsm.Rooms.CreateRoom:input_type -> gsm.CreateRoomReq
	9,  // 8: gsm.Rooms.GetRoomInfo:input_type -> gsm.GetRoomInfoReq
	7,  // 9: gsm.Rooms.CheckRoomExists:input_type -> gsm.CheckRoomExistsReq
	11, // 10: gsm.Rooms.KickPlayer:input_type -> gsm.KickPlayerReq
	6,  // 11: gsm.Rooms.CreateRoom:output_type -> gsm.CreateRoomRsp
	10, // 12: gsm.Rooms.GetRoomInfo:output_type -> gsm.GetRoomInfoRsp
	8,  // 13: gsm.Rooms.CheckRoomExists:output_type -> gsm.CheckRoomExistsRsp
	12, // 14: gsm.Rooms.KickPlayer:output_type -> gsm.KickPlayerRsp
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_gsm_proto_init() }
func file_proto_gsm_proto_init() {
	if File_proto_gsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gsm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlayerStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRoomExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRoomExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gsm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPlayerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gsm_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gsm_proto_goTypes,
		DependencyIndexes: file_proto_gsm_proto_depIdxs,
		EnumInfos:         file_proto_gsm_proto_enumTypes,
		MessageInfos:      file_proto_gsm_proto_msgTypes,
	}.Build()
	File_proto_gsm_proto = out.File
	file_proto_gsm_proto_rawDesc = nil
	file_proto_gsm_proto_goTypes = nil
	file_proto_gsm_proto_depIdxs = nil
}
