// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/landing.proto

package landing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Landing service

func NewLandingEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Landing service

type LandingService interface {
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Landing_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Landing_PingPongService, error)
	Build(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type landingService struct {
	c    client.Client
	name string
}

func NewLandingService(name string, c client.Client) LandingService {
	return &landingService{
		c:    c,
		name: name,
	}
}

func (c *landingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Landing_StreamService, error) {
	req := c.c.NewRequest(c.name, "Landing.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &landingServiceStream{stream}, nil
}

type Landing_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type landingServiceStream struct {
	stream client.Stream
}

func (x *landingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *landingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *landingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *landingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *landingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *landingService) PingPong(ctx context.Context, opts ...client.CallOption) (Landing_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Landing.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &landingServicePingPong{stream}, nil
}

type Landing_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type landingServicePingPong struct {
	stream client.Stream
}

func (x *landingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *landingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *landingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *landingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *landingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *landingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *landingService) Build(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Landing.Build", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Landing service

type LandingHandler interface {
	Stream(context.Context, *StreamingRequest, Landing_StreamStream) error
	PingPong(context.Context, Landing_PingPongStream) error
	Build(context.Context, *Request, *Response) error
}

func RegisterLandingHandler(s server.Server, hdlr LandingHandler, opts ...server.HandlerOption) error {
	type landing interface {
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		Build(ctx context.Context, in *Request, out *Response) error
	}
	type Landing struct {
		landing
	}
	h := &landingHandler{hdlr}
	return s.Handle(s.NewHandler(&Landing{h}, opts...))
}

type landingHandler struct {
	LandingHandler
}

func (h *landingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LandingHandler.Stream(ctx, m, &landingStreamStream{stream})
}

type Landing_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type landingStreamStream struct {
	stream server.Stream
}

func (x *landingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *landingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *landingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *landingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *landingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *landingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.LandingHandler.PingPong(ctx, &landingPingPongStream{stream})
}

type Landing_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type landingPingPongStream struct {
	stream server.Stream
}

func (x *landingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *landingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *landingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *landingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *landingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *landingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *landingHandler) Build(ctx context.Context, in *Request, out *Response) error {
	return h.LandingHandler.Build(ctx, in, out)
}
